#!/usr/bin/env python3
"""ddctl - the simple Datadog Control command line utility

Usage:
  ddctl mute <host>... [--forever | --hours=<hrs>] [--force] [--config]
  ddctl unmute <host>... [--config]
  ddctl downtime (set|remove) <scope>... [--forever | --hours=<hrs>] [--config]
  ddctl downtime list (mine|all) [--config]
  ddctl query host <host> [--config]
  ddctl query tags [--all|--host=<host>] [--config]
  ddctl (-h | --help)
  ddctl --version

Options:
  -h --help     Show this screen.
  --version     Show version.

"""
from docopt import docopt
from brain import *


if __name__ == '__main__':
    args = docopt(__doc__, version='Datadog Control v0.1')
    print(args)
